### ISSUE TITLE
No images.

### ISSUE THREAD

**Issue by adam-vessey** [qadan/qadan.github.io#1]
No images of the burgers. Can haz :hamburger: ?

**Comment by jordandukart** [comment]
+1

**Comment by qadan** [comment]
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`·¸ 
........../'/.../..../......./¨¯\ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........''...\.......... _.·´ 
............\..............( 
..............\.............\...

**Comment by qadan** [comment]
Images are scraped and downloaded and used in the windows now.
