### ISSUE TITLE
2 burger clusters are impossible to separate.

### ISSUE THREAD

**Issue by ackiejoe** [qadan/qadan.github.io#11]
2 burger clusters are impossible to separate regardless of zoom level due to proximity, they are as follows:

2 burgers in Hunters ale house.
2 burgers in Claddagh oyster house.

these may have been a problem with no clustering as well.

**Comment by qadan** [comment]
Looks to be resolved

**Comment by adam-vessey** [comment]
This was broken again in https://github.com/qadan/qadan.github.io/commit/afc929a6aa87f43eeb87fb9c652f82c6b462d036

**Comment by qadan** [comment]
should be resolved again in https://github.com/qadan/qadan.github.io/commit/6797c5fccc1eca9ed7998cba3ee3878360792bd3
