### ISSUE TITLE
Bubble aggregation

### ISSUE THREAD

**Issue by willtp87** [qadan/qadan.github.io#4]
Bubbles should join up at low zoom levels.

**Comment by qadan** [comment]
you should join up at low zoom levels

**Comment by willtp87** [comment]
Your face at low zoom levels!

**Comment by qadan** [comment]
![](http://memecreator.eu/media/created/oag6r9.jpg)

**Comment by qadan** [comment]
inb4 that's not how you use that

**Comment by qadan** [comment]
Moiged
