### ISSUE TITLE
Use requests instead of urllib2.

### ISSUE THREAD

**Issue by adam-vessey** [qadan/qadan.github.io#8]
["requests"](http://docs.python-requests.org/en/latest/) offers something of a nicer interface for making HTTP requests in Python... Just sayin'.

**Comment by willtp87** [comment]
:+1:

**Comment by qadan** [comment]
`urllib2` is just being used to get the body content. what's the practical difference between:

```python
import urllib2
page = urllib2.urlopen(url).read()
```

and

```python
import requests
page = requests.get(url).text
```

?

Also note that this scraper is going to be intensely disgusting. It's going to be grabbing ingredients like this:

```python
def use_witchcraft_to_messily_define_an_ingredient_list(ingredient_string):
    separated_ingredients = ingredient_string.split(' on a ')
    messy_ingredient_list = separated_ingredients[0].split(', ')
    not_messy_ingredient_list = []
    for ingredient in messy_ingredient_list:
        if ingredient.startswith("and "):
            not_messy_ingredient_list.append(ingredient[4:])
        elif " and " in ingredient:
            not_messy_ingredient_list.extend(ingredient.split(" and "))
        else:
            not_messy_ingredient_list.append(ingredient)
    print not_messy_ingredient_list
    return { 'ingredients': not_messy_ingredient_list, 'bun': separated_ingredients[1] }
```

Library choice may be the least inelegant part of this whole mess.

**Comment by adam-vessey** [comment]
I was thinking going forward, when we start trying to scrape images... Could use requests itself to handle the download, instead of making calls out through curl.

**Comment by qadan** [comment]
That can be handled by `urllib2` as well though, no curl-ing, e.g.:

```python
image = urllib2.open(image_url)
local_image = open(some_path_idunno, 'w')
local_image.write(image.read())
```

**Comment by qadan** [comment]
If there was _any_ weirdness at all with the URLs, or with authentication, or with any part of getting responses from peiburgerlove.ca at all, sure, I'd make the switch. But all we want is text and images, and on their site they all use super simple paths with nothing out of the ordinary, no need for authentication, no weird response codes - it's as by-the-book as it gets, so it doesn't sound like this will be necessary for this project

**Comment by qadan** [comment]
In case anybody pops in here with some more sass: I KNOW REQUESTS IS THE BETTER CHOICE, but time is very much of the essence here, so _yes_ we could rework this to grab URLs from the main page, and _yes_ we could establish a framework for adding items to the JSON, and _yes_ we could make it spit fire and shoot lightning and raise the dead but if this doesn't have the core set of features before May 1, all that fancy stuff will go to waste, so I'm going to hammer out the nastiest scraper I can that parses each page accurately, run it one time, grab the JSON and the images, and then maybe next year I can start in February and design something more beautiful-er.
