### ISSUE TITLE
Use geolocation to plot burger radius

### ISSUE THREAD

**Issue by jordandukart** [qadan/qadan.github.io#9]

**Comment by qadan** [comment]
https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

As a reminder for later

**Comment by qadan** [comment]
https://github.com/qadan/qadan.github.io/commit/cf306e0b47c8d9812cf9a4a23f0153cd84ecabf7

some simple, lazy geolocation

TODO: make better
